### ISSUE TITLE
동행복권 사이트 시스템 점검 중일 때 코맨드를 실행하면 적절한 에러 표시하기

### ISSUE THREAD

**Issue by gilbok** [roeniss/dhlottery-api#14]
<img width="463" alt="Screenshot 2023-04-04 at 00 12 02" src="https://user-images.githubusercontent.com/1301040/229580549-69587439-c9fd-4b98-8031-9a0ea1562b9a.png">

현재는 아래와 같은 에러가 발생합니다.

```bash
Traceback (most recent call last):
  File "/opt/homebrew/bin/dhapi", line 8, in <module>
    sys.exit(main())
  File "/opt/homebrew/lib/python3.9/site-packages/dhapi/main.py", line 5, in main
    entrypoint()
  File "/opt/homebrew/lib/python3.9/site-packages/dhapi/router/router.py", line 9, in entrypoint
    ctrl = Lotto645Controller(arg_parser.get_user_id(), arg_parser.get_user_pw())
  File "/opt/homebrew/lib/python3.9/site-packages/dhapi/purchase/lotto645_controller.py", line 7, in __init__
    self.client = LotteryClient()
  File "/opt/homebrew/lib/python3.9/site-packages/dhapi/client/lottery_client.py", line 34, in __init__
    self._set_default_session()
  File "/opt/homebrew/lib/python3.9/site-packages/dhapi/client/lottery_client.py", line 46, in _set_default_session
    raise KeyError("JSESSIONID cookie is not set in response")
KeyError: 'JSESSIONID cookie is not set in response'
```

에러 코드를 정의해서 출력하면 좋을 것 같습니다.

**Comment by roeniss** [comment]
더블체크 감사합니다. 안그래도 반영하려던 중이었습니다 :bow:

https://github.com/roeniss/dhlottery-api/pull/9

**Comment by roeniss** [comment]
`pip install dhapi --upgrade` 하시면 v1.2.2 받으실 수 있으실거예요!
