### ISSUE TITLE
python 3.11 에서 실행 불가

### ISSUE THREAD

**Issue by roeniss** [roeniss/dhlottery-api#50]
### 응급처치법 

[pyenv](https://github.com/pyenv/pyenv) 등을 사용해서 3.8 버전으로 실행

### 에러로그

```
Traceback (most recent call last):
  File "/opt/homebrew/bin/dhapi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dhapi/main.py", line 5, in main
    entrypoint()
  File "/opt/homebrew/lib/python3.11/site-packages/dhapi/router/router.py", line 7, in entrypoint
    arg_parser = ArgParser()
                 ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dhapi/router/arg_parser.py", line 25, in __init__
    installed_version, _ = get_versions()
                           ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/dhapi/router/version_checker.py", line 20, in get_versions
    dist = JohnnyDist(PACKAGE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/johnnydep/lib.py", line 81, in __init__
    self.import_names, self.metadata = _get_info(
                                       ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cachetools/__init__.py", line 702, in wrapper
    v = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/johnnydep/lib.py", line 477, in _get_info
    data = pipper.get(
           ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/johnnydep/pipper.py", line 236, in get
    target, _headers = _download_dist(url, scratch_file, index_url, extra_index_url)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/johnnydep/pipper.py", line 105, in _download_dist
    target, _headers = urlretrieve(url, scratch_file, auth=auth)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/johnnydep/compat.py", line 38, in urlretrieve
    res = opener.open(url, data=data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 503, in open
    req = Request(fullurl, data)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 322, in __init__
    self.full_url = url
    ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 348, in full_url
    self._parse()
  File "/opt/homebrew/Cellar/python@3.11/3.11.4/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'dhapi-2.0.0-py3-none-any.whl.metadata'
```

**Comment by dfdgsdfg** [comment]
3.8.17에서 동일 에러 발생
```
dhapi -U dfdgsdfg -P -K lotto645 -T buy -M auto -C 5
Traceback (most recent call last):
  File "/Users/user/.asdf/installs/python/3.8.17/bin/dhapi", line 8, in <module>
    sys.exit(main())
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/site-packages/dhapi/main.py", line 5, in main
    entrypoint()
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/site-packages/dhapi/router/router.py", line 7, in entrypoint
    arg_parser = ArgParser()
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/site-packages/dhapi/router/arg_parser.py", line 25, in __init__
    installed_version, _ = get_versions()
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/site-packages/dhapi/router/version_checker.py", line 20, in get_versions
    dist = JohnnyDist(PACKAGE_NAME)
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/site-packages/johnnydep/lib.py", line 81, in __init__
    self.import_names, self.metadata = _get_info(
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/site-packages/cachetools/__init__.py", line 702, in wrapper
    v = func(*args, **kwargs)
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/site-packages/johnnydep/lib.py", line 477, in _get_info
    data = pipper.get(
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/site-packages/cachetools/__init__.py", line 737, in wrapper
    v = func(*args, **kwargs)
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/site-packages/johnnydep/pipper.py", line 236, in get
    target, _headers = _download_dist(url, scratch_file, index_url, extra_index_url)
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/site-packages/johnnydep/pipper.py", line 105, in _download_dist
    target, _headers = urlretrieve(url, scratch_file, auth=auth)
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/site-packages/johnnydep/compat.py", line 38, in urlretrieve
    res = opener.open(url, data=data)
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/urllib/request.py", line 509, in open
    req = Request(fullurl, data)
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/urllib/request.py", line 328, in __init__
    self.full_url = url
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/urllib/request.py", line 354, in full_url
    self._parse()
  File "/Users/user/.asdf/installs/python/3.8.17/lib/python3.8/urllib/request.py", line 383, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'dhapi-2.0.0-py3-none-any.whl.metadata'
```
