### ISSUE TITLE
1장 구매 시 에러 발생

### ISSUE THREAD

**Issue by chomman** [roeniss/dhlottery-api#57]
1장 구매 시 다음과 같은 에러가 발생합니다.

```sh
$ dhapi buy_lotto645 -g
Traceback (most recent call last):
  File "/Users/hapi/.pyenv/versions/3.8.18/bin/dhapi", line 8, in <module>
    sys.exit(main())
  File "/Users/hapi/.pyenv/versions/3.8.18/lib/python3.8/site-packages/dhapi/main.py", line 5, in main
    entrypoint()
  File "/Users/hapi/.pyenv/versions/3.8.18/lib/python3.8/site-packages/dhapi/router/router.py", line 7, in entrypoint
    arg_parser = ArgParser()
  File "/Users/hapi/.pyenv/versions/3.8.18/lib/python3.8/site-packages/dhapi/router/arg_parser.py", line 84, in __init__
    credentials = config_util.get(group="dhapi", context="credentials", profile=self._args.profile[0])
  File "/Users/hapi/.pyenv/versions/3.8.18/lib/python3.8/site-packages/seunggabi_core_python/util/config_util.py", line 36, in get
    return config._sections[profile]
KeyError: 'default'
```

**Comment by monolith-taehyun** [comment]
credentials 설정을 잘못하여 발생한 문제였습니다.

**Comment by chomman** [comment]
credentials 설정을 잘못 하여 발생한 문제였습니다.

**Comment by roeniss** [comment]
@chomman 다행이네요!
